(define (problem foodtruck_5)
 (:domain foodtruck)
(:objects
parkinglot1 parkinglot2 - parkinglot
)

(:init 
(= (whitespace) (new-bit-matrix false 5 15))
(= (buildings) (new-bit-matrix false 5 15))
(= (gridheight) 5)
(= (gridwidth) 15)
(= (whitespace) (set-index whitespace true 1 1))
(= (whitespace) (set-index whitespace true 1 2))
(= (whitespace) (set-index whitespace true 1 3))
(= (whitespace) (set-index whitespace true 1 4))
(= (whitespace) (set-index whitespace true 1 5))
(= (whitespace) (set-index whitespace true 1 6))
(= (whitespace) (set-index whitespace true 1 7))
(= (whitespace) (set-index whitespace true 1 8))
(= (whitespace) (set-index whitespace true 1 9))
(= (whitespace) (set-index whitespace true 1 10))
(= (whitespace) (set-index whitespace true 1 11))
(= (whitespace) (set-index whitespace true 1 12))
(= (whitespace) (set-index whitespace true 1 13))
(= (whitespace) (set-index whitespace true 1 14))
(= (whitespace) (set-index whitespace true 1 15))
(= (whitespace) (set-index whitespace true 2 1))
(= (whitespace) (set-index whitespace true 2 2))
(= (whitespace) (set-index whitespace true 2 3))
(= (whitespace) (set-index whitespace true 2 4))
(= (whitespace) (set-index whitespace true 2 5))
(= (whitespace) (set-index whitespace true 2 6))
(= (whitespace) (set-index whitespace true 2 7))
(= (whitespace) (set-index whitespace true 2 8))
(= (whitespace) (set-index whitespace true 2 9))
(= (whitespace) (set-index whitespace true 2 10))
(= (whitespace) (set-index whitespace true 2 11))
(= (whitespace) (set-index whitespace true 2 12))
(= (whitespace) (set-index whitespace true 2 13))
(= (whitespace) (set-index whitespace true 2 14))
(= (whitespace) (set-index whitespace true 2 15))
(= (whitespace) (set-index whitespace true 3 15))
(= (whitespace) (set-index whitespace true 4 1))
(= (whitespace) (set-index whitespace true 4 2))
(= (whitespace) (set-index whitespace true 4 3))
(= (whitespace) (set-index whitespace true 4 4))
(= (whitespace) (set-index whitespace true 4 5))
(= (whitespace) (set-index whitespace true 4 6))
(= (whitespace) (set-index whitespace true 4 7))
(= (whitespace) (set-index whitespace true 4 8))
(= (whitespace) (set-index whitespace true 4 9))
(= (whitespace) (set-index whitespace true 4 10))
(= (whitespace) (set-index whitespace true 4 11))
(= (whitespace) (set-index whitespace true 4 12))
(= (whitespace) (set-index whitespace true 4 13))
(= (whitespace) (set-index whitespace true 4 14))
(= (whitespace) (set-index whitespace true 4 15))
(= (whitespace) (set-index whitespace true 5 1))
(= (whitespace) (set-index whitespace true 5 2))
(= (whitespace) (set-index whitespace true 5 3))
(= (whitespace) (set-index whitespace true 5 4))
(= (whitespace) (set-index whitespace true 5 5))
(= (whitespace) (set-index whitespace true 5 6))
(= (whitespace) (set-index whitespace true 5 7))
(= (whitespace) (set-index whitespace true 5 8))
(= (whitespace) (set-index whitespace true 5 9))
(= (whitespace) (set-index whitespace true 5 10))
(= (whitespace) (set-index whitespace true 5 11))
(= (whitespace) (set-index whitespace true 5 12))
(= (whitespace) (set-index whitespace true 5 13))
(= (whitespace) (set-index whitespace true 5 14))
(= (whitespace) (set-index whitespace true 3 1))
(= (buildings) (set-index buildings true 3 2))
(= (buildings) (set-index buildings true 3 3))
(= (buildings) (set-index buildings true 3 4))
(= (buildings) (set-index buildings true 3 5))
(= (buildings) (set-index buildings true 3 6))
(= (buildings) (set-index buildings true 3 7))
(= (buildings) (set-index buildings true 3 8))
(= (buildings) (set-index buildings true 3 9))
(= (buildings) (set-index buildings true 3 10))
(= (buildings) (set-index buildings true 3 11))
(= (buildings) (set-index buildings true 3 12))
(= (buildings) (set-index buildings true 3 13))
(= (buildings) (set-index buildings true 3 14))
(= (whitespace) (set-index whitespace true 5 15))
(= (yloc koreantruck) 1) 
(= (xloc koreantruck) 1) 
(= (yloc parkinglot1) 1) 
(= (xloc parkinglot1) 1)

(= (yloc student) 3) 
(= (xloc student) 1)

(= (yloc lebanesetruck) 5) 
(= (xloc lebanesetruck) 15) 
(= (yloc parkinglot2) 5) 
(= (xloc parkinglot2) 15)

(= (xloc mexicantruck) -1)
(= (yloc mexicantruck) -1)
)
(:goal (true)) 
)